### PR TITLE
Include syslog application

### PR DESCRIPTION
**Pull request by ypaq**

### CODE REVIEW

**Comment by ypaq** [comment]
bump

**Comment by mrallen1** [comment]
I'll be looking at this today. Thanks for the PR.

**Comment by Vagabond** [comment]
Make sure this change is pulled into the 2.1 branch and a new version is tagged. I think this change is fine, though.

**Comment by mrallen1** [comment]
Built riak with this change and did some basic tests. Looks good. Merged against the 2.1 branch and tagged as `2.1.2`

Thanks again for the PR. Sorry it took so long to merge.

**Comment by ypaq** [comment]
Thanks! :+1:

**Pull request closed without merging**
