### PR TITLE
update rebar to ver 2.5.1

### PR DESCRIPTION
**Pull request by tsantero**
On OTP 17.4 I'm seeing compile time errors when building lager_syslog as a dependency of a rebar3 based project. Upgrading rebar seems to fix it.

The error in question:

```
==> syslog (compile)
Uncaught error in rebar_core: {'EXIT',
                               {badarg,
                                [{re,split,
                                  [[118,99,115,95,105,110,102,111,95,109,115,
                                    103,95,48,95,61,32,111,110,32,37,123,27,
                                    91,51,54,109,37,125,109,97,115,116,101,
                                    114,37,123,27,91,51,51,109,37,125,32,9679,
                                    37,123,27,91,51,49,109,37,125,32,9679,37,
                                    123,27,91,48,48,109,37,125],
                                   "=",
                                   [{return,list},{parts,2}]],
                                  [{file,"re.erl"},{line,170}]},
                                 {rebar_port_compiler,'-os_env/0-lc$^0/1-0-',
                                  1,[]},
                                 {rebar_port_compiler,'-os_env/0-lc$^0/1-0-',
                                  1,[]},
                                 {rebar_port_compiler,os_env,0,[]},
                                 {rebar_port_compiler,setup_env,1,[]},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2,[]},
                                 {rebar_core,setup_envs,2,[]},
                                 {rebar_core,execute,4,[]}]}}
```

This PR is pointed toward the 2.1 branch, as master appears to be stale at this point.

### CODE REVIEW

**Comment by jonmeredith** [comment]
Hey @tsantero 

I tried building locally and noticed a difference on how it handles the deps - make clean or make tests don't recurse into deps.

```
jons-mbp13:lagersyslog17 jmeredith$ git branch
* (HEAD detached at tsantero/bugfix/upgrade-rebar)
  master
jons-mbp13:lagersyslog17 jmeredith$ make clean
./rebar clean
==> lagersyslog17 (clean)
jons-mbp13:lagersyslog17 jmeredith$ git checkout master
Previous HEAD position was 35f04bb... update rebar to ver 2.5.1
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
jons-mbp13:lagersyslog17 jmeredith$ make clean
./rebar clean
==> goldrush (clean)
==> lager (clean)
==> syslog (clean)
==> lagersyslog17 (clean)
```

Do you get the same thing... old rebars are old
```
jons-mbp13:lagersyslog17 jmeredith$ ./rebar --version
rebar version: 2 date: 20110624_180307 vcs: git 3e41385
```

**Comment by jonmeredith** [comment]
Also breaks R14 support on Travis - which I can live without :)

**Comment by mrallen1** [comment]
@tsantero @jonmeredith I just tested this on my workstation and confirm Jon's comment about the recursion. Must be switch somewhere where new rebar ignores deps and old rebar just honeybadgers right on through.

**Comment by tsantero** [comment]
I had forgotten about this. Sorry for leaving it open so long with no response, @jonmeredith 

Closing as this issue is solved elsewhere.

**Pull request closed without merging**
